spring.application.name=Connectly-member-service

# JWT Config
jwt.secret=27db492b2b786841d4b899deb459d6fb9df0c247df59d648ab7c6d0054accb8b
jwt.expiration=86400000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://Hrithik0216:Hrithik0216@cluster0.m321jgb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=connectly

# Server Configuration
server.port=8096
